name: CustomerReport
description: Customer Reporting
version: 0.0.1
author: wgfox@foxfusion.net
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: customerreport
  parentArtefactID: wgfoxfoxfusionnetteam
  buildSystem: wheel
  author: null
  createdAt: '2024-10-22 05:39:56'
pipelines:
  pipelines/CustomerPricing:
    name: CustomerPricing
    description: ''
    author: wgfox@foxfusion.net
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-10-22 05:39:56'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-10-22 05:39:56'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2024-10-22T05:39:56.304873Z'
  name: plibMaven
  version: 8.2.1
  id: '1342962922'
  createdAt: '2024-10-22T05:39:56.304873Z'
  type: plibMaven
- modifiedAt: '2024-10-22T05:39:56.304873Z'
  name: plibPypi
  version: 1.9.16
  id: '1524172387'
  createdAt: '2024-10-22T05:39:56.304873Z'
  type: plibPypi
projectDependencies:
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.8
    isDefault: true
    author: null
    createdAt: '2024-10-22 05:38:48'
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.30
    isDefault: true
    author: null
    createdAt: '2024-10-22 05:38:48'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
